server:
  port: 8085
  servlet:
    context-path: /api
    # paths:
    # login: /login
    # auth: /auth
    
  error:
    include-details: always

# Configuraciones de la web          
  # mvc:
  #   view:
  #     prefix: resources/templates
  #     suffix: html
               
# Conexión a MySQL

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mantenimientovehdb
    username: postgres
    password: ${BD_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver

##Configuraciones JPA - Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
security:
  jwt:
    secret: 6a45sdf44fs46f
    issuer: Main
    ttlMillis: 604800000

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
