server:
  port: 8888
  
spring:
  application:
    name: ms-admin-config-server
    
#Configuracion Local
  profiles:
    active: native
    
  cloud:
    config:
      server:
        native:
          search-locations: ///D:\PROYECTO AA4\ms-gestion-config-data
      
 
      